# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pull Request Validation

on:
    pull_request:
        branches:
            - master
            - development

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v1
                with:
                    java-version: 16
            -   uses: gradle/gradle-build-action@v2
                with:
                    arguments: build
                    gradle-version: wrapper
